#!/usr/bin/env node
/**
 * Exchanges a Zoho Self Client grant code for a long-lived refresh token,
 * and writes the credentials to .env.
 *
 *   node scripts/zoho-token.mjs
 *
 * The grant code is single-use and expires within minutes of being generated,
 * so have it ready before running this. Nothing is sent anywhere except Zoho.
 */
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';

const DATA_CENTRES = {
  eu: { accounts: 'https://accounts.zoho.eu', api: 'https://www.zohoapis.eu' },
  com: { accounts: 'https://accounts.zoho.com', api: 'https://www.zohoapis.com' },
  'com.au': { accounts: 'https://accounts.zoho.com.au', api: 'https://www.zohoapis.com.au' },
  in: { accounts: 'https://accounts.zoho.in', api: 'https://www.zohoapis.in' },
  jp: { accounts: 'https://accounts.zoho.jp', api: 'https://www.zohoapis.jp' },
  ca: { accounts: 'https://accounts.zohocloud.ca', api: 'https://www.zohoapis.ca' },
};

// Interactive when run in a terminal; when stdin is piped, read the answers
// up front so the script also works non-interactively.
const piped = !stdin.isTTY;
const pipedLines = piped
  ? (await new Promise((resolve) => {
      let data = '';
      stdin.setEncoding('utf8');
      stdin.on('data', (c) => (data += c));
      stdin.on('end', () => resolve(data));
    }))
      .split('\n')
      .map((l) => l.trim())
  : [];

const rl = piped ? null : createInterface({ input: stdin, output: stdout });
let pipeIndex = 0;
const ask = async (q, fallback = '') => {
  if (piped) return pipedLines[pipeIndex++] || fallback;
  const answer = (await rl.question(q)).trim();
  return answer || fallback;
};

console.log('\nZoho CRM setup: exchange a Self Client code for a refresh token\n');

const dcKey = (
  await ask(`Data centre [${Object.keys(DATA_CENTRES).join(' / ')}] (default eu): `, 'eu')
).toLowerCase();
const dc = DATA_CENTRES[dcKey];
if (!dc) {
  console.error(`\nUnknown data centre "${dcKey}". Pick one of: ${Object.keys(DATA_CENTRES).join(', ')}`);
  rl?.close();
  process.exit(1);
}

const clientId = await ask('Client ID: ');
const clientSecret = await ask('Client Secret: ');
const code = await ask('Generated code: ');
rl?.close();

if (!clientId || !clientSecret || !code) {
  console.error('\nAll three values are required. Nothing written.');
  process.exit(1);
}

console.log(`\nExchanging code at ${dc.accounts} ...`);

const response = await fetch(`${dc.accounts}/oauth/v2/token`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: new URLSearchParams({
    grant_type: 'authorization_code',
    client_id: clientId,
    client_secret: clientSecret,
    code,
  }),
});

const body = await response.json().catch(() => ({}));

// Zoho reports most failures as HTTP 200 with an `error` key.
if (body.error || !body.refresh_token) {
  const hints = {
    invalid_code:
      'The code was already used, has expired, or belongs to a different data centre.\n' +
      '  Generate a fresh one in the API Console and run this again straight away.',
    invalid_client: 'Client ID or Secret is wrong, or was created in a different data centre.',
    invalid_client_secret: 'Client Secret is wrong.',
  };
  console.error(`\nFailed: ${body.error ?? `HTTP ${response.status}`}`);
  if (hints[body.error]) console.error(`  ${hints[body.error]}`);
  if (!body.error) console.error(`  ${JSON.stringify(body).slice(0, 300)}`);
  process.exit(1);
}

const lines = [
  '# Zoho CRM. Generated by scripts/zoho-token.mjs. Do not commit this file.',
  `ZOHO_CLIENT_ID=${clientId}`,
  `ZOHO_CLIENT_SECRET=${clientSecret}`,
  `ZOHO_REFRESH_TOKEN=${body.refresh_token}`,
  `ZOHO_ACCOUNTS_DOMAIN=${dc.accounts}`,
  `ZOHO_API_DOMAIN=${dc.api}`,
  '',
].join('\n');

if (existsSync('.env') && readFileSync('.env', 'utf8').includes('ZOHO_REFRESH_TOKEN')) {
  writeFileSync('.env.zoho.new', lines, { mode: 0o600 });
  console.log('\n.env already has Zoho values, so the new ones are in .env.zoho.new instead.');
} else {
  writeFileSync('.env', lines, { mode: 0o600 });
  console.log('\nWritten to .env');
}

console.log('\nAdd these three to Vercel (Settings, Environment Variables):\n');
console.log(`  ZOHO_CLIENT_ID      ${clientId}`);
console.log(`  ZOHO_CLIENT_SECRET  ${'*'.repeat(12)}  (copy from .env)`);
console.log(`  ZOHO_REFRESH_TOKEN  ${'*'.repeat(12)}  (copy from .env)`);
if (dcKey !== 'eu') {
  console.log(`\nYou are not on the EU data centre, so also add:\n`);
  console.log(`  ZOHO_ACCOUNTS_DOMAIN  ${dc.accounts}`);
  console.log(`  ZOHO_API_DOMAIN       ${dc.api}`);
}
console.log('\nThen: npm run dev, and submit the form at /contact to check it lands in CRM.\n');
